Bugfix to StatSig when time zone aware data is passed
Summary:
When time zone aware data is passed to StatSig's `fit_predict()` method and we are using the corrected t-scores, the algorithm raises the following TypeError from pd.infer_freq [here](https://fburl.com/code/j0nkqf7x) because pd.infer_freq cannot handle time zone aware data:
```
TypeError: cannot infer freq from a non-convertible dtype on a Series of datetime64[ns, US/Pacific]
```

We can use Kats' native TimeSeriesData.infer_freq_robust() to compute data granularity and get around this issue.

Reviewed By: peiyizhang

Differential Revision: D39335671

fbshipit-source-id: 0148c458fe8430ae40291b8300bb1be3a2a1be87