Add typing-extensions requirement for Python 3.7
When running the project on Python 3.7, only installing requirements
with:
```
pip install -r requirements.txt
```

The project fails with the following error:
```
$ python -c 'from kats.models.prophet import ProphetModel'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/src/kats/__init__.py", line 6, in <module>
    from . import data  # noqa # usort: skip
  File "/src/kats/data/__init__.py", line 6, in <module>
    from . import utils  # noqa
  File "/src/kats/data/utils.py", line 29, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
```

This is because, for Python 3.7, `typing-extensions` is needed as
`Literal` is not included in stdlib's `typing`.